### PR TITLE
Allow providing a custom setting file, overriding the default setting…

### PR DESCRIPTION
**Pull request by stylesuxx**
…s at build time #142

No functional change. Resulting hex files are byte compatible to base branch.

### CODE REVIEW

**Comment by hyp0dermik-code** [comment]
Works fine, but I note the folder must be in the cloned repo to be included in the Docker mount. Due to this I think it would be best to prescribe a folder and add it to the .gitignore - see #202

**Comment by stylesuxx** [comment]
Yeah, good point. Not sure if adding it to git ignore is going to be enough of a hint as to where to put it, so we could either add an empty skeleton Folder `CustomSettings` with a short *md file or expand the documentation accordingly.

**Comment by hyp0dermik-code** [comment]
> Yeah, good point. Not sure if adding it to git ignore is going to be enough of a hint as to where to put it, so we could either add an empty skeleton Folder `CustomSettings` with a short *md file or expand the documentation accordingly.

Yea I'll expand the documentation when this is all merged
I was thinking of simply:
```
mkdir user
cp -rf /src/Settings/ user/
```
This creates the directory `user/Settings` where you  can edit settings accordingly. 
The `user` directory is ignored by Git

Then build using...

**Comment by hyp0dermik-code** [comment]
There could be some debate on directory naming and structure

**Review by hyp0dermik-code — APPROVED** [review]

**Comment by stylesuxx** [comment]
@hyp0dermik-code This for example would have been a PR where I would have rather squashed the commits since the addition of the user folder is rather to be seen as a part of the "main feature" of this PR and and a commit just for that seems like overkill.

(just for reference, no harm done ;-)

**Pull request merged**
