### PR TITLE
Update Docker Debian version

### PR DESCRIPTION
**Pull request by hyp0dermik-code**
See #203 

Merge after #201 and #202

### CODE REVIEW

**Comment by hyp0dermik-code** [comment]
This will likely break the current Github build environment and require the regeneration of the .wine folder

Docker image grows by 600MB from 1.2GB to 1.8GB

**Comment by stylesuxx** [comment]
Could you rebase this branch on latest develop please?

**Comment by stylesuxx** [comment]
@saidinesh5 will updating the Dockerfile trigger automatic re-generation [builder package](https://github.com/orgs/bird-sanctuary/packages/container/package/bluejay-builder)?

I would not like to fiddle with that if we can keep it in working condition, I remember that the initial setup was a bit of a PITA...

**Comment by saidinesh5** [comment]
We pushed the builder container manually to the repo iirc. But yeah let's avoid the docker file update ..

**Comment by hyp0dermik-code** [comment]
> We pushed the builder container manually to the repo iirc. But yeah let's avoid the docker file update ..

So there would be technically no harm in updating the Docker file?

The disadvantage is it makes the environment harder to replicate, but the need to change the Dockerfile can be documented in the meantime

Shall we close it and document it for the meantime, and I'll leave the issue open for further investigation?

**Comment by stylesuxx** [comment]
Yeah, if we pushed it manually, then there should not be a problem. For now let's leave this issue open.

I am not too familiar with the package part and how it is supposed to regenerate things. Since we do not have an action that is doing anything to it, I'd guess it won't update - unless there is some magic happening that I am unaware of.

**Pull request closed without merging**
