### PR TITLE
[0.20.1] Min/max startup power set to 1010/1020 by default

### PR DESCRIPTION
**Pull request by damosvil**

### CODE REVIEW

**Review by stylesuxx — APPROVED** [review]

**Comment by stylesuxx** [comment]
Configurator adjustment reference: https://github.com/stylesuxx/esc-configurator/issues/410

**Comment by stylesuxx** [comment]
For RC3...

**Review by hyp0dermik-code — APPROVED** [review]
The safest option but impact to be observed

**Comment by stylesuxx** [comment]
> The safest option but impact to be observed

I think it's better if we err on the side of safety here...
By now most whoop people already know they will most likely need to adjust it - so I think the community can give the correct tips to help others with bigger builds out here.

**Pull request merged**
