### PR TITLE
Added DSHOT 150 configuration step for EFM8BB21 and EFM8BB51

### PR DESCRIPTION
**Pull request by damosvil**
This commit enables DSHOT 150 on BB21 and BB51 targets.

This pr tries to bid an option to relieve all possible stress generated by comms on the zero cross detection algorithm while keeping the possibility to update motor pwm at 2khz.

### CODE REVIEW

**Comment by stylesuxx** [comment]
This is more of a convenience feature for testing and debugging, rather than for using in a productive environment - right?

**Comment by damosvil** [comment]
Yes, I think I should not have created the pr. I will remove the pr. Just for trying things

**Comment by damosvil** [comment]
Not for production. Only for research

**Comment by stylesuxx** [comment]
I think it's OK to have the PR - IF - it will work in production too. I mean, if someone set's DSHOT150 in prod by accident it should still be working. We can document that DSHOT150 is purely for development. Alternatively we could add a "dev" flag which would enable such thing for dev builds.

I did not mean to shut down your PR - was just asking out of interest.

**Pull request closed without merging**
