### PR TITLE
Implemented pwm frequency configurable by eeprom setting

### LINKED ISSUE #9: "Variable" PWM
Allows the PWM frequency to be adjusted as a setting and does not require the firmware to be re-flashed.

This is actually also part of the branch mentioned in #8

### PR DESCRIPTION
**Pull request by damosvil**
This pr adds pwm configurable by the eeprom setting

### CODE REVIEW

**Comment by damosvil** [comment]
@stylesuxx The comming days I will test it before moving from draft

**Review by stylesuxx — CHANGES_REQUESTED** [review]
Alright, this looks good to me. On first sights it seems to be more changes than it actually are but I guess git is not best in picking up only the white space changes in some sections.

What needs to be done is to bump the layout to 207, then I can add the functionality in the configurator. Also I don't see the variable being added to the "EEPROM" - or am I missing something?

**Comment by damosvil** [comment]
The eeprom setting is Pgm_Pwm_Freq. It already existed, preloaded with [24, 48, 96] range of values.
I will make the whitespace cleanup soon

**Comment by damosvil** [comment]
Fixed whitespaces

**Comment by damosvil** [comment]
No smoke during workbench testing and hovering and the first flight. All seems to work, but I am going to do more testing on my side

**Comment by damosvil** [comment]
I made more flights abusing pretty hard my Meteor 65 and extracted several logs.
There were no problems and no smoke.
Please, use this blackbox explorer branch if you want to inspect the logs:
https://github.com/betaflight/blackbox-log-viewer/pull/625

[PWM_FREQ_SETTING_BTFL_BLACKBOX_LOG_Meteor65_20230213_191041.zip](https://github.com/bird-sanctuary/bluejay/files/10725130/PWM_FREQ_SETTING_BTFL_BLACKBOX_LOG_Meteor65_20230213_191041.zip)
, and no smoke.
[PWM_FREQ_SETTING_BTFL_BLACKBOX_LOG_Meteor65_20230213_185103.zip](https://github.com/bird-sanctuary/bluejay/files/10725129/PWM_FREQ_SETTING_BTFL_BLACKBOX_LOG_Meteor65_20230213_185103.zip)

**Comment by damosvil** [comment]
@stylesuxx This pr has a subset of functionalities of variable_pwm one. Please consider discarding it in favour of the latest one

**Comment by stylesuxx** [comment]
Closing this in favor of #67

**Pull request closed without merging**
